jaffle_shop:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'aether_energy_analytics.duckdb'
      threads: 24
      schema: 'testing'
    prod:
      type: duckdb
      path: 'aether_energy_analytics.duckdb'
      threads: 24
      schema: 'prod'
