aether_energy_analytics:

  target: dev
  outputs:
    dev:
      type: sqlite
      path: 'aether_energy_analytics.db'
      threads: 24
      schema: 'testing'
    prod:
      type: sqlite
      path: 'aether_energy_analytics.db'
      threads: 24
      schema: 'prod'
