version: 2

sources:
  - name: aether_energy_analytics
    schema: main  # which schema am I referring to here???
    tables:
      - name: customer_feedback
      - name: customers
      - name: energy_consumption

## These models here, since we are in staging, are the models post transformation - after they have been transformed from the source

models:
  - name: stg_customers
    # description: "Raw customer data"
    columns:
      - name: customer_id
        description: "The unique identifier for a customer"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "The name of the customer"
        tests:
          - not_null
      - name: region
        description: "The region of the customer"
        tests:
          - not_null
      - name: age
        description: "Age of the customer"
        tests:
          - not_null
      # Note: Gender is excluded here

  - name: stg_customer_feedback
    # description: "Raw customer feedback data"
    columns:
      - name: feedback_date
        description: "The date the feedback was given"
      - name: customer_id
        description: "The unique identifier for a customer"
        tests:
          - not_null
      - name: rating
        description: "The rating given by the customer"
        tests:
          - not_null
      - name: comments
        description: "Comments given by the customer"

  - name: stg_energy_consumption
    # description: "Raw energy consumption data"
    columns:
      - name: timestamp
        description: "The timestamp of the energy consumption reading"
      - name: customer_id
        description: "The unique identifier for a customer"
        tests:
          - not_null
      - name: energy_usage_kWh
        description: "The amount of energy used in kWh"
        tests:
          - not_null



# models:
#   - name: stg_customers
#     # description: "Raw customer data"
#     columns:
#       - name: customer_id
#         description: "The unique identifier for a customer"
#         tests:
#           - unique
#           - not_null
#       - name: customer_name
#         description: "The name of the customer"
#         tests:
#           - not_null
#       - name: region
#         description: "The region of the customer"
#         tests:
#           - not_null
#        - name: age
#         description: "age of the customer"
#         tests:
#           - not_null
#       # note we are excluding gender here 
#   - name: stg_customer_feedback
#     # description: "Raw customer feedback data"
#     columns:
#       - name: feedback_date
#         description: "The date the feedback was given"
#       - name: customer_id
#         description: "The unique identifier for a customer"
#         tests:
#           - not_null
#       - name: rating
#         description: "The rating given by the customer"
#         tests:
#           - not_null
#       - name: comments
#         description: "Comments given by the customer"
#   - name: stg_energy_consumption
#     # description: "Raw energy consumption data"
#     columns:
#       - name: timestamp
#         description: "The timestamp of the energy consumption reading"
#       - name: customer_id
#         description: "The unique identifier for a customer"
#         tests:
#           - not_null
#       - name: energy_usage_kWh
#         description: "The amount of energy used in kWh"
#         tests:
#           - not_null



















# models:
#   - name: stg_customer_feedback
#     description: "This table contains staged customer feedback data"
#     columns:
#       - name: feedback_date
#         description: "Date of feedback"
#         tests:
#           - not_null

#   - name: stg_customers
#     description: "This table contains staged customer data"
#     columns:
#       - name: customer_id
#         description: "Primary key for customers"
#         tests:
#           - unique
#           - not_null

#   - name: stg_energy_consumption
#     description: "This table contains staged energy consumption data"
#     columns:
#       - name: energy_usage_kWh
#         description: "Energy usage in kWh"
#         tests:
#           - not_null

  

  
# # models:
# #   - name: stg_customer_feedback
# #     description: "This table contains staged customer feedback data"
# #     columns:
# #       - name: timestamp
# #         description: "Date of feedback"
# #         tests:
# #           - not_null
# #       - name: customer_id
# #         description: "Foreign key to the customers table"
# #         tests:
# #           - not_null
# #       - name: rating
# #         description: "Customer rating"
# #         tests:
# #           - not_null
          
# #   - name: stg_energy_consumption
# #     description: "This table contains staged energy consumption data"
# #     columns:
# #       - name: timestamp
# #         description: "Timestamp of energy consumption"
# #         tests:
# #           - not_null
# #       - name: customer_id
# #         description: "Foreign key to the customers table"
# #         tests:
# #           - not_null
# #       - name: energy_usage
# #         description: "Energy usage in kWh"
# #         tests:
# #           - not_null

# #   - name: stg_customers
# #     description: "This table contains staged customer data"
# #     columns:
# #       - name: customer_id
# #         description: "Primary key for customers"
# #         tests:
# #           - unique
# #           - not_null
# #       - name: name
# #         description: "Name of the customer"
# #       - name: age
# #         description: "Age of the customer"
# #       - name: region
# #         description: "Region where the customer is located"