name: Docker Image CI

on:
  workflow_dispatch:
    # 
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --rm -t aether_energy_analytics .
    - name: run dbt 
      run: docker container run aether_energy_analytics --rm
