sources:
  - name: aether_energy_analytics
    schema: main  # which schema am I referring to here???
    tables:
      - name: customers
      - name: energy_consumption
      - name: customer_feedback